img_size: 224
num_classes: 7
model_type: 'large'
depth:
  small: 4
  base: 6
  large: 8

face_landback_checkpoint: './models/pretrain/mobilefacenet_model_best.pth.tar'
ir_checkpoint: './models/pretrain/ir50.pth'

use_parallel: True